### ISSUE TITLE
It is impossible to stop sending notification emails for a repository

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-notify-plugin#20]
Once you have configured a repository to send emails to a contact, it is impossible (via GUI) to remove all recipients.

This seems to be a conscious design decision: 

https://github.com/scm-manager/scm-notify-plugin/blob/36ae3fcad0b6517d4354b09b5a7fc19a6425615c/src/main/js/NotifyConfigurationForm.tsx#L53-L56

I would argue, it should be possible to allow via GUI the removal of all recipients, thus stopping the notifications.

Current workaround: remove all recipients, then use the developer tools to enable the submit button by hand, then click on it.

**Comment by pfeuffer** [comment]
Kudos for the workaround ;-)
I definitely think you're right: Either there should be a switch to turn off notifications for the repository or you should be able to delete all recipients. This check is superfluous in my view.

**Comment by sdorra** [comment]
Fixed with version 2.0.3 of the plugin.
